[Doc] Add Python docstring for some operators
taichi-dev/taichi pull request #2586
Opened 2021-07-26 08:49 UTC by beginlner

Related issue = #2579

2021-07-26 08:49 UTC, beginlner commented
/format

2021-07-27 11:51 UTC, ljcc0930 commented on python/taichi/lang/ops.py
> +    """
```suggestion
    """Negate function.

    Args:
        a: A number.

    Returns:
        The negative value of number a.
    """
```
```suggestion
        
```
Explaining with some words?

2021-07-27 11:52 UTC, ljcc0930 commented
Explaining the functions with some words?

2021-07-28 05:46 UTC, beginlner commented
> Explaining the functions with some words?
> 
> e.g.:
> 
> ```
>     """Negate function.
>     Args:
>         a: A number.
>     Returns:
>         The negative value of number a.
>     """
> ```

ok

2021-07-28 05:47 UTC, beginlner commented
/format

2021-07-28 08:12 UTC, beginlner commented
/format

2021-07-28 08:19 UTC, Leonz5288 requested changes
I believe ti.field is better than ti.Expr which is pretty vague about the type being passed in. Also, ti.field is in parallel relationship with ti.Matrix. @ljcc0930

2021-07-28 08:33 UTC, strongoier commented
> I believe ti.field is better than ti.Expr which is pretty vague about the type being passed in. Also, ti.field is in parallel relationship with ti.Matrix. @ljcc0930

The type of `ti.field` is `ti.Expr` for now. I'm currently refactoring this so the confusion about these types may be resolved in the future.

2021-07-29 05:24 UTC, ljcc0930 approved these changes
LGTM!

2021-07-29 05:27 UTC, ljcc0930 commented on python/taichi/lang/ops.py
> +        a (Union[ti.Expr, ti.Matrix]): A number or a maxtrix.
```suggestion
        a (Union[:class:`~taichi.lang.expr.Expr`, :class:`~taichi.lang.matrix.Matrix`]): A number or a matrix.
```

2021-07-29 05:28 UTC, ljcc0930 commented on python/taichi/lang/ops.py
> +        a (Union[ti.Expr, ti.Matrix]): A number or a maxtrix.
```suggestion
        a (Union[:class:`~taichi.lang.expr.Expr`, :class:`~taichi.lang.matrix.Matrix`]): A number or a matrix.
```

2021-07-29 05:48 UTC, k-ye approved these changes
Great!

2021-07-29 10:46 UTC, merged