[Lang] Add deepcopy for ndarray
taichi-dev/taichi pull request #3473
Opened 2021-11-12 03:52 UTC by qiao-bo

Add deepcopy and copy_from for ndarray

2021-11-12 03:53 UTC, qiao-bo commented
/format

2021-11-15 03:38 UTC, strongoier approved these changes
Looks great! Only a few nits.

2021-11-15 03:38 UTC, strongoier commented on python/taichi/lang/_ndarray.py
>              import numpy as np  # pylint: disable=C0415
```suggestion
```

2021-11-15 03:38 UTC, strongoier commented on python/taichi/lang/_ndarray.py
> +            ndarray: The result ndarray.
```suggestion
            Ndarray: The result ndarray.
```

2021-11-15 03:38 UTC, strongoier commented on tests/python/test_ndarray.py
> +    assert y.m == x.n
```suggestion
    assert y.m == x.m
```

2021-11-15 05:40 UTC, qiao-bo commented
/format

2021-11-15 09:44 UTC, YuCrazing requested changes

2021-11-16 13:44 UTC, qiao-bo commented
/format

2021-11-17 01:05 UTC, YuCrazing approved these changes
Thanks!

2021-11-17 01:11 UTC, merged