[cuda] Enable block splitting for cuda caching memory allocator
taichi-dev/taichi pull request #3677
Opened 2021-12-02 03:21 UTC by qiao-bo

Related issue = #3634

This enables the reuse of buffers with larger size.

2021-12-02 03:21 UTC, qiao-bo commented
/format

2021-12-02 08:53 UTC, strongoier requested changes
Looks great! Only some tiny issues :-)

2021-12-02 09:39 UTC, qiao-bo commented on taichi/backends/cuda/cuda_caching_allocator.cpp
> +    if ((remaining_sz > 0) && (remaining_sz % taichi_page_size == 0)) {
right! iroundup guarantees its always aligned, thx!

2021-12-02 09:49 UTC, qiao-bo commented
/format

2021-12-02 10:10 UTC, qiao-bo commented
/format

2021-12-03 07:23 UTC, strongoier approved these changes
LGTM!

2021-12-03 07:23 UTC, strongoier commented on taichi/backends/cuda/cuda_caching_allocator.cpp
> +      // only split if the remaining sz is page aligned
```suggestion
```

2021-12-03 08:41 UTC, merged