[Lang] #2610 add typed build assign
taichi-dev/taichi pull request #3709
Opened 2021-12-04 22:47 UTC by woooodyye

Related issue = #

2021-12-05 05:38 UTC, strongoier commented
Hi @woooodyye. Which PR is the version you would like to get reviewed, this or #3701?

2021-12-05 05:41 UTC, woooodyye commented
hi, can I get this PR draft reviewed ? I think #3701 has formatting issues. Thanks. @strongoier

2021-12-05 07:13 UTC, strongoier requested changes
Great!

2021-12-05 07:13 UTC, strongoier commented on python/taichi/lang/ast/ast_transformer.py
> +            if str(var.ptr.get_ret_type()) != annotation:
1. Why do we use `str` here?
2. Could you also add a test for this invalid case?

2021-12-05 07:13 UTC, strongoier commented on python/taichi/lang/ast/ast_transformer.py
> +        annotation = getattr(node.annotation, 'attr')
Why not `node.annotation.attr`?

2021-12-05 07:13 UTC, strongoier commented on python/taichi/lang/ast/ast_transformer.py
> +        if is_static_assign:
We should not allow annotated static assign.

2021-12-05 07:16 UTC, strongoier commented
/format

2021-12-06 04:43 UTC, woooodyye commented
please ignore the review request

2021-12-06 07:08 UTC, woooodyye commented
Right Now. Since annotations are not considered as variables, we need to explicitly define a primitive type as a value for the primitive types to be considered as variables.

For Instance:
`a: ti.i32 = 1`
would not work.

Instead, we need to do something like
```
my_int = ti.i32
a : my_int = 1
```

### Note: the primitive type you declare doesn't necessarily need to be the type annotation you want to use, It's totally fine to do
```
my_int = ti.i32
a : ti.f32 = 1.
b : ti.f64 = 2
.......
```

The whole point of this `my_int = ti.i32` declaration statement is to introduce ti.primitivetypes into the global variables.

2021-12-06 07:22 UTC, strongoier requested changes
Great work! Only some nits.

2021-12-06 07:22 UTC, strongoier commented on python/taichi/lang/ast/ast_transformer.py
> +
```suggestion
```

2021-12-06 07:22 UTC, strongoier commented on python/taichi/lang/ast/ast_transformer.py
> +        """Build basic assginment like this: target : annotation = value.
```suggestion
        """Build an annotated assignment like this: target: annotation = value.
```

2021-12-06 07:22 UTC, strongoier commented on python/taichi/lang/ast/ast_transformer.py
> +    def build_ann_assign_basic(ctx, target, value, is_static_assign,
I suggest renaming it as `build_assign_annotated` to match other names like `build_assign_basic`, `build_assign_unpack`.

2021-12-06 07:22 UTC, strongoier commented on python/taichi/lang/ast/ast_transformer.py
> +
```suggestion
```

2021-12-06 07:22 UTC, strongoier commented on tests/python/test_assign.py
> +        #need to introduce it
```suggestion
        # need to introduce ti as a global var
```

2021-12-06 07:22 UTC, strongoier commented on tests/python/test_assign.py
> +    with pytest.raises(ti.lang.exception.TaichiCompilationError) as e:
```suggestion
    with pytest.raises(ti.TaichiCompilationError):
```

2021-12-06 07:22 UTC, strongoier commented on tests/python/test_assign.py
> +    assert e.type is ti.lang.exception.TaichiCompilationError
```suggestion
```
This is redundant.

2021-12-07 01:53 UTC, strongoier approved these changes
LGTM!

2021-12-07 02:46 UTC, merged