[Lang] Support sparse solver datatype configuration
taichi-dev/taichi pull request #3733
Opened 2021-12-07 07:29 UTC by FantasyVR

Related issue = #2906

2021-12-08 07:43 UTC, Hanke98 reviewed
Sorry for the delayed response.
LGTM mostly, I only have one point that I am not so sure

BTW, should we add some test cases against data type?

2021-12-08 07:43 UTC, Hanke98 commented on taichi/program/sparse_solver.cpp
> +      {"f32", "float32"}, {"f64", "float64"}};
Is float64 type supported now? Should we add float64 in `solver_factory`? (or maybe later after float64 is fully supported.

2021-12-09 04:05 UTC, FantasyVR commented
/format

2021-12-09 06:21 UTC, strongoier requested changes
Would you fix the compilation error on the Windows platform?

2021-12-12 08:03 UTC, strongoier approved these changes
LGTM! Only one suggestion below.

2021-12-12 08:03 UTC, strongoier commented on taichi/program/sparse_solver.cpp
> +  static const std::unordered_map<std::string, std::string> dt_map = {
Using strings to refer to types (e.g. "f32") is not good practice, so maybe in the future some refactoring needs to be done here :-)

2021-12-13 05:36 UTC, merged