[llvm] [bug] Support atomic min/max for unsigned int type
taichi-dev/taichi pull request #3779
Opened 2021-12-12 13:47 UTC by g1n0st

Related issue = close #3751

2021-12-12 13:48 UTC, g1n0st commented
/format

2021-12-13 05:09 UTC, strongoier requested changes
Looks great!

2021-12-13 05:09 UTC, strongoier commented on tests/python/test_atomic.py
> +            ti.atomic_max(x[0], x[1])
```suggestion
            ti.atomic_max(x[0], x[I])
```
Is this the original intention?

2021-12-13 05:09 UTC, strongoier commented on tests/python/test_atomic.py
> +            ti.atomic_min(x[0], x[1])
ditto

2021-12-13 05:20 UTC, g1n0st commented on tests/python/test_atomic.py
> +            ti.atomic_max(x[0], x[1])
Fixed. I think both are OK.

2021-12-13 05:20 UTC, g1n0st commented on tests/python/test_atomic.py
> +            ti.atomic_min(x[0], x[1])
Fixed.

2021-12-13 05:31 UTC, strongoier approved these changes
LGTM!

2021-12-13 06:19 UTC, ailzhang approved these changes
Thanks for fixing it!

2021-12-13 07:21 UTC, merged