[Example] Improve mass_spring_3d_ggui.py
taichi-dev/taichi pull request #3879
Opened 2021-12-25 10:01 UTC by AlexBrown42

Made some minor improvements there:
1. Better collision handling
2. Bending springs
3. Added dashpot_damping
4. Reset animation when the cloth moves completely out of the window

2021-12-25 10:01 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/taichi-dev/taichi?pullRequest=3879) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/taichi-dev/taichi?pullRequest=3879) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/taichi-dev/taichi?pullRequest=3879) it.</sub>

2021-12-26 17:47 UTC, AmesingFlank commented on cmake/TaichiCore.cmake
> -
is this included accidentally? :D

2021-12-26 17:49 UTC, AmesingFlank commented
Hi! Thanks for these improvements. The file `mass_spring_3d_ggui.py` is used as an accompanying code sample for a [blog article](https://docs.taichi.graphics/blog), so I think it's the best to not modify it. Instead, how about we add your improved program in a new file, perhaps `mass_spring_3d_ggui_improved.py`?

2021-12-27 17:09 UTC, AmesingFlank approved these changes

2021-12-30 03:17 UTC, bobcao3 requested changes
Thanks for optimizing! Just need to remove the accidental cmake change and then rename this file

2022-05-31 11:03 UTC, neozhaoliang approved these changes
LGTM!

2022-06-01 01:47 UTC, merged