[Lang] Matrix argument supprot for ti.kernel
taichi-dev/taichi pull request #3905
Opened 2021-12-29 08:22 UTC by XiangyunYang

Related issue = #3904 
I do some work for this. I consider the matrix as a list of scalar value to pass it

2021-12-29 08:22 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/taichi-dev/taichi?pullRequest=3905) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/taichi-dev/taichi?pullRequest=3905) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/taichi-dev/taichi?pullRequest=3905) it.</sub>

2021-12-29 09:53 UTC, strongoier commented
Welcome to the Taichi community! I suggest reading our [contribution guide](https://docs.taichi.graphics/lang/articles/contribution/contributor_guide). The current step is to solve code format & style issues :-)

2021-12-29 13:02 UTC, mzmzm commented
Thanks! I have fixed my code format error.

2021-12-30 07:10 UTC, strongoier requested changes
Great work! Only some nits.

2021-12-30 07:10 UTC, strongoier commented on python/taichi/lang/kernel_arguments.py
> +    return tmp
This way of constructing `Matrix` will be deprecated soon :-) 
```suggestion
    return Matrix([[decl_scalar_arg(matrixtype.dtype) for _ in matrixtype.m] for _ in matrixtype.n])
```

2021-12-30 07:28 UTC, mzmzm commented on tests/python/test_matrix_arg.py
> +        assert mat1[0, 0] == 1
1. Yes. It's a typo here. 
2. I will change it soon.

2021-12-30 07:37 UTC, mzmzm commented
/format

2021-12-31 02:38 UTC, strongoier approved these changes
LGTM!

2021-12-31 02:39 UTC, merged