[doc] Add doc about difference between taichi and python programs
taichi-dev/taichi pull request #3996
Opened 2022-01-11 10:39 UTC by lin-hitonami

Related issue = #

2022-01-12 15:22 UTC, k-ye commented on docs/lang/articles/basic/difference_between_taichi_and_python_programs.md
> +Although taichi uses Python as the frontend, there are some differences between taichi and python programs.
nit: Taichi

2022-01-12 15:22 UTC, k-ye commented on docs/lang/articles/basic/difference_between_taichi_and_python_programs.md
> +- If a taichi function has a return statement, return type annotation is optional.
Let's not suggest this. I believe type annotation for functions will be equally important once we support real function.

2022-01-13 10:49 UTC, Vissidarte-Herman requested changes

2022-01-14 09:35 UTC, Leonz5288 commented on docs/lang/articles/basic/differences_between_taichi_and_python_programs.md
> +Main differences are:
Might sounds better with "Major differences:"

2022-01-14 09:42 UTC, Leonz5288 commented on docs/lang/articles/basic/differences_between_taichi_and_python_programs.md
> +- If a taichi kernel has a return statement, it must have return type annotation.
These two lines are somewhat repeating? May be better with:

In a Taichi kernel, return statement must appear with the existence of return type annotation, vice versa.

2022-01-14 09:42 UTC, Leonz5288 commented on docs/lang/articles/basic/differences_between_taichi_and_python_programs.md
> +- If a taichi kernel/function does not have a return statement, it must not have return type annotation.
I believe 'taichi' has to be capitalized as 'Taichi'?

2022-01-14 09:46 UTC, Leonz5288 commented on docs/lang/articles/basic/differences_between_taichi_and_python_programs.md
> +Taichi does not have a runtime implementation of `in` currently. So, operator `in` and `not in` only works in  [static scope](/lang/articles/advanced/meta#static-scope) (inside `ti.static()`).
`So` -> `Therefore`
`So` cannot connect two complete sentences.

2022-01-14 09:47 UTC, Leonz5288 commented on docs/lang/articles/basic/differences_between_taichi_and_python_programs.md
> +and does not support set comprehension.
`but` might be better than `and`?

2022-01-14 09:49 UTC, Leonz5288 reviewed
Some suggestions on texts.

2022-01-17 03:31 UTC, Leonz5288 commented on docs/lang/articles/basic/differences_between_taichi_and_python_programs.md
> +- If a taichi kernel has a return statement, it must have return type annotation.
Make sense

2022-01-20 05:24 UTC, Vissidarte-Herman requested changes

2022-01-20 05:30 UTC, lin-hitonami commented
/format

2022-01-25 08:03 UTC, ailzhang approved these changes
LGTM!

2022-01-25 08:20 UTC, merged