[doc] Improve operators page
taichi-dev/taichi pull request #4073
Opened 2022-01-20 03:33 UTC by lin-hitonami

Related issue = #

2022-01-20 03:41 UTC, qiao-bo approved these changes
LGTM! Thanks

2022-01-20 03:55 UTC, strongoier approved these changes
LGTM!

2022-01-26 08:15 UTC, Vissidarte-Herman requested changes

2022-01-26 08:15 UTC, Vissidarte-Herman commented on docs/lang/articles/basic/operator.md
> +For element-wise conditional operation on Taichi vectors and matrices,
```suggestion
For element-wise conditional operations on Taichi vectors and matrices,
```

2022-01-26 08:15 UTC, Vissidarte-Herman commented on docs/lang/articles/basic/operator.md
> +The return value has a range that is type dependent.
The range of the returned value is type-specific.

2022-01-26 08:30 UTC, lin-hitonami commented
Don't merge before the next version releases.

2022-01-26 09:41 UTC, qiao-bo approved these changes
One tiny nit: it's better to split the CPU/CUDA into two columns in the table, as we did in the type system page ;/ Other than that, looks great, thanks!

2022-02-15 01:28 UTC, merged