[Docs] Update PyTorch interface documentation
taichi-dev/taichi pull request #4311
Opened 2022-02-16 23:57 UTC by victoriacity

2022-02-16 23:57 UTC, victoriacity commented
/format

2022-02-17 05:50 UTC, Vissidarte-Herman requested changes
Some very minor corrections. Not trying to split hairs...

2022-02-17 05:50 UTC, Vissidarte-Herman commented on docs/lang/articles/basic/external.md
> +before passed into a Taichi kernel:
```suggestion
before being passed into a Taichi kernel:
```

2022-02-25 11:05 UTC, k-ye commented
Is this ready to merge?

2022-03-02 03:17 UTC, Vissidarte-Herman approved these changes
LGTM!

2022-03-02 03:24 UTC, victoriacity commented
@k-ye This PR is now ready to merge.

2022-03-02 07:52 UTC, merged