[Doc] Update global_settings.md
taichi-dev/taichi pull request #5764
Opened 2022-08-15 03:14 UTC by neozhaoliang

2022-08-15 10:25 UTC, Vissidarte-Herman requested changes
Minor style updates.

2022-08-15 10:25 UTC, Vissidarte-Herman commented on docs/lang/articles/reference/global_settings.md
> +- To disable offline cache of the compiled kernels: `ti.init(offline_cache=False)`. This will prohibit Taichi from saving compiled kernels to your local disk.
```suggestion
- To disable offline cache of the compiled kernels: `ti.init(offline_cache=False)`. This prevents Taichi from saving compiled kernels to your local disk.
```

Please always use present tense.

2022-08-15 10:59 UTC, ailzhang commented on docs/lang/articles/reference/global_settings.md
> +- To disable offline cache of the compiled kernels: `ti.init(offline_cache=False)`. This prevents Taichi from saving compiled kernels to your local disk.
and also the env variable?

2022-08-16 11:06 UTC, ailzhang approved these changes

2022-08-16 11:06 UTC, merged