[doc] Refactor kernels and functions
taichi-dev/taichi pull request #5943
Opened 2022-09-01 08:03 UTC by neozhaoliang

2022-09-01 10:36 UTC, yuanming-hu approved these changes
Cool! Details need more work, but the content LGTM in general!

2022-09-01 10:36 UTC, yuanming-hu commented on docs/lang/articles/kernels/syntax.md
> +Let's see an example:
```suggestion
You can call Taichi kernel directly from Python code. You can also call Taichi functions from Taichi kernels, but not directly from Python code.
Let's see an example:
```

2022-09-01 10:36 UTC, yuanming-hu commented on docs/lang/articles/kernels/syntax.md
> +Here by "out of the Taichi scope" we mean the scope that is not inside a kernel or a Taichi function. We shall also use the term *Python scope* for short of this.
Let's highlight the definition of Taichi/Python scope :-)

2022-09-02 05:21 UTC, Olinaaaloompa requested changes

2022-09-02 05:21 UTC, Olinaaaloompa commented on docs/lang/articles/kernels/syntax.md
>  The return values of a Taichi function can be scalar, `ti.Matrix`, `ti.Vector`, `ti.Struct`, and more. Note that:
```suggestion
The return values of a Taichi function can be scalars, `ti.Matrix`, `ti.Vector`, `ti.Struct`, or others. Note that:
```

2022-09-02 05:21 UTC, Olinaaaloompa commented on docs/lang/articles/kernels/syntax.md
> +print(inv_square(1.0))  # syntax error!
```suggestion
print(inv_square(1.0))  # Syntax error!
```

2022-09-02 05:21 UTC, Olinaaaloompa commented on docs/lang/articles/kernels/syntax.md
> +   Taichi scope corresponds to the device side in CUDA.
```suggestion
   The Taichi scope corresponds to the device side in CUDA.
```

2022-09-02 05:21 UTC, Olinaaaloompa commented on docs/lang/articles/kernels/syntax.md
> +   Python scope corresponds to the host side in CUDA.
```suggestion
   The Python scope corresponds to the host side in CUDA.
```

2022-09-02 05:21 UTC, Olinaaaloompa commented on docs/lang/articles/kernels/syntax.md
> +A kernel is the entry point from which Taichi's runtime takes control and the smallest unit for runtime execution. You can define multiple kernels in your program, and these kernels are *independent*
```suggestion
As the smallest execution unit in Taichi, a kernel is the entry point from which Taichi's runtime takes control. You call a kernel the same way you call a Python function and can switch back and forth between Taichi's runtime and Python's virtual machine.
```

2022-09-02 05:21 UTC, Olinaaaloompa commented on docs/lang/articles/kernels/syntax.md
> +You must *not* call a kernel from inside another kernel or from inside a Taichi function. You can only call a kernel directly or from inside a native Python function.
```suggestion
You must *not* call a kernel from inside another kernel or from inside a Taichi function. You can only call a kernel directly or from inside a native Python function. In other words, you can only call a kernel from inside the Python scope.
```

2022-09-02 08:02 UTC, Olinaaaloompa requested changes

2022-09-02 08:02 UTC, Olinaaaloompa commented on docs/lang/articles/kernels/syntax.md
> +Here by "out of the Taichi scope" we mean the scope that is not inside a kernel or a Taichi function. We shall also use the term *Python scope* for short of this.
```suggestion
The Taichi function should have fallen in the Taichi scope, a concept as opposed to the "Python scope". 
```

2022-09-02 08:02 UTC, Olinaaaloompa approved these changes

2022-09-02 08:11 UTC, merged