[Doc] Refactor field
taichi-dev/taichi pull request #6006
Opened 2022-09-07 08:15 UTC by neozhaoliang

2022-09-08 12:16 UTC, Olinaaaloompa requested changes

2022-09-08 12:24 UTC, Olinaaaloompa requested changes

2022-09-08 12:24 UTC, Olinaaaloompa commented on docs/lang/articles/basic/field.md
> +Since `paticle_field.mass` is a field that consists of all the `mass` members of the structs in `paticle_field`, we can also call its `fill()` method to set them to a specific value all at once:
```suggestion
Considering that `paticle_field.mass` is a field consisting of all the `mass` members of the structs in `paticle_field`, we can also call its `fill()` method to set the members to a specific value all at once:
```

2022-09-08 13:17 UTC, neozhaoliang commented on docs/lang/articles/basic/field.md
> +- If the vectors in the field have dimension <=4, then you can also use vector swizzling indices `xyzw` or `rgba` to access the components of the vectors:
"provided that the vector has no more than four dimensions:"

It should be "provided that the dimension of the vector is no more than four".

2022-09-13 03:41 UTC, Olinaaaloompa approved these changes

2022-09-13 09:21 UTC, yuanming-hu reviewed
A few comments.

2022-09-13 09:21 UTC, yuanming-hu commented on docs/lang/articles/basic/field.md
> +Once a field is declared, Taichi automatically assigns an initial value of zero to its elements. But we do not recommend using this undefined behavior.
```suggestion
Once a field is declared, Taichi automatically assigns an initial value of zero to its elements.
```

Zero-initialization is defined behavior.

2022-09-13 09:21 UTC, yuanming-hu commented on docs/lang/articles/basic/field.md
> +  ```
I feel like this is too verbose. The readers should understand what a high-dimensional array is. Let's remove the 3D case here.

2022-09-13 09:21 UTC, yuanming-hu commented on docs/lang/articles/basic/field.md
> +    The memory layout of the field `f_2d` will be like:
```suggestion
    An illustration of f_2d is below:
```
Let's avoid using `memory layout` here, which has a different meaning. Just use `An illustration of f_2d is below` is good enough.

2022-09-13 09:21 UTC, yuanming-hu commented on docs/lang/articles/basic/field.md
> +The memory layout of `f` will be like:
Avoid the term `memory layout`.

2022-09-13 09:21 UTC, yuanming-hu commented on docs/lang/articles/basic/field.md
> +  volumetric_field[i, j, k].rgb = 1, 2, 3  # ibid.
Avoid `ibid`. Not clear what that means.

2022-09-13 10:43 UTC, Olinaaaloompa requested changes

2022-09-13 10:43 UTC, Olinaaaloompa commented on docs/lang/articles/basic/field.md
> +    An illustration of `f_1d` shown is below:
```suggestion
    An illustration of `f_1d` is shown below:
```

2022-09-13 10:43 UTC, Olinaaaloompa commented on docs/lang/articles/basic/field.md
> ++ To declare a 0D scalar field, set its shape to the empty tuple `()`.
```suggestion
+ To declare a 0D scalar field, set its shape to the empty tuple `()`:
```

2022-09-13 10:43 UTC, Olinaaaloompa commented on docs/lang/articles/basic/field.md
> ++ To declare a 2D scalar field, set the size of its first two dimensions, i.e. the number of rows and columns, respectively. For example, the following code defines a 2D scalar field of shape (3, 6),
```suggestion
+ To declare a 2D scalar field, set the sizes of its first two dimensions, i.e., the number of rows and columns, respectively. For example, the following code defines a 2D scalar field of shape (3, 6), which has 3 rows and 6 columns:
```

2022-09-13 10:43 UTC, Olinaaaloompa commented on docs/lang/articles/basic/field.md
> +You can access a member of an element in a struct field in either of the following ways: "index-first"  or "name-first".
```suggestion
You can access a member of an element in a struct field in either of the following ways: "index-first" or "name-first".
```

2022-09-14 10:12 UTC, Olinaaaloompa approved these changes

2022-09-14 11:29 UTC, merged