[Doc] Refactor global settings
taichi-dev/taichi pull request #6071
Opened 2022-09-15 09:31 UTC by neozhaoliang

2022-09-15 16:46 UTC, yuanming-hu reviewed
Thanks, but there are still many undocumented global settings: https://github.com/taichi-dev/taichi/blob/9d27b94ec04943528c4028da4f50fa6dfc25d000/taichi/python/export_lang.cpp#L138-L241

You may want to pick a subset of frequently used options. E.g., `cpu_max_num_threads` is one option that is frequently used but not documented.

Related logic: https://github.com/taichi-dev/taichi/blob/760d501be883dd0ea1c424be186fbbd00aae0dcd/python/taichi/lang/misc.py#L313

2022-09-16 09:00 UTC, Vissidarte-Herman commented
I'm still not quite clear as to what "global" means here. Can either of you shed more light on this?

2022-09-16 09:10 UTC, neozhaoliang commented
@Vissidarte-Herman Added some explanations for the term "global".

2022-09-22 04:11 UTC, Olinaaaloompa requested changes

2022-09-22 04:11 UTC, Olinaaaloompa commented on docs/lang/articles/reference/global_settings.md
> +In summary, when calling `ti.init()`, Taichi will execute the following steps to initialize a specific configuration: (we use the `arch` argument to illustrate this)
```suggestion
Generally, when calling `ti.init()`, Taichi executes the following steps to initialize a specific configuration. We use the `arch` argument as an example:
```

2022-09-22 08:04 UTC, Olinaaaloompa requested changes

2022-09-23 02:23 UTC, neozhaoliang commented on docs/lang/articles/reference/global_settings.md
> +        Directory holding the offline cached files.
@Olinaaaloompa Should change set a directory -> specify a directory

2022-09-23 02:26 UTC, neozhaoliang commented on docs/lang/articles/reference/global_settings.md
> +Below are some environment variables that you can set to customize your Taichi program, they overlap but are not in one-to-one correspondence with the `ti.init()` arguments listed above:
@Olinaaaloompa  The meaning of the original version is changed: some environment settings do not map to `init` arguments.

2022-09-23 02:29 UTC, neozhaoliang commented on docs/lang/articles/reference/global_settings.md
> +        Enable/disable triggering GDB when Taichi crashes, e.g. `ti.init(gdb_trigger=True)`.
I'm not sure the word "silence" is a good choice here.

2022-09-23 11:51 UTC, Vissidarte-Herman requested changes
LGTM! Thank you! Some minor editorial changes.

2022-09-23 11:51 UTC, Vissidarte-Herman commented on docs/lang/articles/reference/global_settings.md
> +The call `ti.init()` is indispensable in every Taichi program. It allows you to customize your Taichi runtime by passing arguments to it or setting environment variables. Each argument or environment
```suggestion
The call `ti.init()` is indispensable in every Taichi program. Taichi allows you to customize your Taichi runtime by passing arguments to `ti.init()` or setting environment variables. Each argument or environment variable controls one specific behavior of the Taichi runtime. For example, the argument `arch` specifies the backend, and the argument `debug` decides whether to run the program in debug mode. The document [Hello, World!](../get-started/index.md) gives a brief introduction to this function, and this document provides more details.
```

2022-09-23 11:51 UTC, Vissidarte-Herman commented on docs/lang/articles/reference/global_settings.md
> +Generally, when calling `ti.init()`, Taichi executes the following steps to initialize a specific configuration. We use the `arch` argument as an example:
```suggestion
Generally, when you call `ti.init()`, Taichi executes the following steps to initialize a specific configuration. We use the `arch` argument as an example:
```
'calling' takes 'Taichi' as its subject, which is incorrect.

2022-09-23 11:51 UTC, Vissidarte-Herman commented on docs/lang/articles/reference/global_settings.md
> +1. Firstly, Taichi looks for the argument that is passed to `ti.init()`. In this case, after Taichi reads `ti.init(arch=cuda)`, it chooses CUDA as the backend and omits the environment variable.
```suggestion
1. Taichi looks for the arguments passed to `ti.init()`. In this case, after Taichi reads `ti.init(arch=cuda)`, it chooses CUDA as the backend and omits the environment variable.
```
I believe argument should be in plural form here.

2022-09-23 11:51 UTC, Vissidarte-Herman commented on docs/lang/articles/reference/global_settings.md
> +2. If no argument is found, Taichi checks the corresponding environment variable. In this case, if `arch` is not specified but replaced by the environment variable `export TI_ARCH=cuda`, Taichi still
```suggestion
2. If no argument is found, Taichi checks the corresponding environment variable. In this case, if `arch` is not specified but the environment variable is set to `export TI_ARCH=cuda`, Taichi chooses CUDA as the backend.
```

2022-09-23 11:51 UTC, Vissidarte-Herman commented on docs/lang/articles/reference/global_settings.md
> +3. If no customized setting is found, Taichi uses a default configuration. In this case, if neither the argument `arch` is specified nor the environment variable `TI_ARCH` is found, Taichi adopts the
```suggestion
3. If no customized setting is found, Taichi uses a default configuration. In this case, if neither the argument `arch` is specified nor an environment variable `TI_ARCH` is found, Taichi adopts the default backend `arch=ti.cpu`.
```

2022-09-23 11:51 UTC, Vissidarte-Herman commented on docs/lang/articles/reference/global_settings.md
> +Below are some most frequently used configurations you can set with the `ti.init()` call:
```suggestion
Following are some frequently used configurations that the `ti.init()` method call supports:
```

2022-09-23 12:56 UTC, Olinaaaloompa commented on docs/lang/articles/reference/global_settings.md
> +Below are some environment variables that you can set to customize your Taichi program, they overlap but are not in one-to-one correspondence with the `ti.init()` arguments listed above:
Have rephrased. Please check the sentence again.

2022-09-23 13:34 UTC, neozhaoliang commented on docs/lang/articles/reference/global_settings.md
> +Below are some environment variables that you can set to customize your Taichi program, they overlap but are not in one-to-one correspondence with the `ti.init()` arguments listed above:
"Interchangeable" is a bit obscure here. Let's say "not all of them have corresponding arguments of the `init` function"?

2022-09-23 13:36 UTC, Vissidarte-Herman approved these changes
LGTM

2022-09-26 08:34 UTC, Olinaaaloompa approved these changes
LGTM

2022-09-26 08:35 UTC, merged