[Doc] Refactor Profiler
taichi-dev/taichi pull request #6142
Opened 2022-09-22 10:56 UTC by Olinaaaloompa

Issue: #

### Brief Summary

2022-09-23 08:10 UTC, Olinaaaloompa commented on docs/lang/articles/performance_tuning/profiler.md
> +The profile produces the following output:
```suggestion
The profiler produces the following output:
```

2022-09-23 10:53 UTC, Vissidarte-Herman requested changes

2022-09-23 10:53 UTC, Vissidarte-Herman commented on docs/lang/articles/performance_tuning/profiler.md
> +High-performance numerical computation is one of the key features of Taichi. To better measure the performance of Taichi programs, Taichi provides profiling tools that collect both hardware and Taich
```suggestion
To facilitate code debugging and code optimization, Taichi provides a set of profiling tools, which collect hardware and Taichi-related information to quantify program performance and analyze where bottleneck occurs.
```
- Feature: selling point. By using "feature", you changed the intended meaning. 
- "To better measure" is not authentic English. 
-  I spent some time sorting out the causal relation in the sentence.

2022-09-23 10:53 UTC, Vissidarte-Herman commented on docs/lang/articles/performance_tuning/profiler.md
>  3. To clear records in this profiler, call `ti.profiler.clear_kernel_profiler_info()`.
```suggestion
3. To clear the records in this profiler, call `ti.profiler.clear_kernel_profiler_info()`.
```

2022-09-23 10:53 UTC, Vissidarte-Herman commented on docs/lang/articles/performance_tuning/profiler.md
> +The profiler produces the following output:
```suggestion
The profiler outputs the following:
```

2022-09-23 11:31 UTC, Vissidarte-Herman requested changes

2022-09-23 11:31 UTC, Vissidarte-Herman commented on docs/lang/articles/performance_tuning/profiler.md
> +Currently, Taichi provides two profilers:
```suggestion
Currently, Taichi provides two profiling tools:
```

2022-09-23 11:31 UTC, Vissidarte-Herman commented on docs/lang/articles/performance_tuning/profiler.md
> +- `KernelProfiler` analyzes the performance of Taichi kernels (device). Its advanced mode provides detailed low-level performance metrics (such as memory bandwidth consumption).
```suggestion
- `KernelProfiler` analyzes the performance of Taichi kernels (device). Its advanced mode provides detailed low-level performance metrics, such as memory bandwidth consumption.
```

2022-09-23 11:31 UTC, Vissidarte-Herman commented on docs/lang/articles/performance_tuning/profiler.md
>  1. To enable this profiler, set `kernel_profiler=True` in `ti.init`.
```suggestion
1. To enable this profiler, set `kernel_profiler=True` when calling `ti.init()`. 
```

2022-09-23 11:31 UTC, Vissidarte-Herman commented on docs/lang/articles/performance_tuning/profiler.md
>      - In `'trace'` mode, the profiler shows you a list of kernels that were launched on hardware during the profiling period.
```suggestion
    - In `'trace'` mode, the profiler shows you a list of kernels launched on hardware during the profiling period.
```

2022-09-23 11:31 UTC, Vissidarte-Herman commented on docs/lang/articles/performance_tuning/profiler.md
> +- You are recommended to run performance profiling several times to observe the minimum or average execution time.
"You are recommended to do" is not grammatical. Use either of the following:
- Taichi recommends doing xxx
- It is recommended that you do

2022-09-23 11:31 UTC, Vissidarte-Herman commented on docs/lang/articles/performance_tuning/profiler.md
> +- You are recommended to run performance profiling several times to observe the minimum or average execution time.
```suggestion
- Taichi recommends running performance profiling multiple times to observe the minimum or average execution time.
```

2022-09-23 11:31 UTC, Vissidarte-Herman commented on docs/lang/articles/performance_tuning/profiler.md
> +- Currently, `kernel_profiler` only supports CPU and CUDA. Ensure that you call `ti.sync()` before performance profiling if the program is running on GPU.
```suggestion
- `kernel_profiler` supports CPU and CUDA only. Ensure that you call `ti.sync()` before performance profiling if your program is running on GPU.
```

2022-09-23 11:31 UTC, Vissidarte-Herman commented on docs/lang/articles/performance_tuning/profiler.md
> +- A kernel that has been fully optimized by the compiler would not generate profiling records.
```suggestion
- A kernel that is fully optimized by the compiler does not generate profiling records.
```

2022-09-23 13:27 UTC, neozhaoliang approved these changes
LGTM!

2022-09-26 08:28 UTC, Vissidarte-Herman approved these changes
LGTM

2022-09-26 08:29 UTC, merged