[Doc] Add doc for math module
taichi-dev/taichi pull request #6145
Opened 2022-09-23 02:12 UTC by neozhaoliang

2022-09-23 07:22 UTC, Olinaaaloompa requested changes

2022-09-23 07:22 UTC, Olinaaaloompa commented on docs/lang/articles/math/math.md
> +The number of precision bits of these matrix types will be determined by `default_fp` and `default_ip` in your `ti.init()` call. For example, if `ti.init(default_fp=ti.f64)` is called, then the types
```suggestion
The number of precision bits of such a type is determined by `default_fp` or `default_ip` in `ti.init()`. For example, if `ti.init(default_fp=ti.f64)` is called, then `vec2/vec3/vec4` and `mat2/mat3/mat4` defined in the Taichi scope all have 64-bit floating-point precision.
```

2022-09-23 07:27 UTC, neozhaoliang commented on docs/lang/articles/math/math.md
> +1. Commonly-used mathematical functions that are analogous to those in Python's built-in `math` module.
I'm afraid we should not use "identical" here.

2022-09-23 07:32 UTC, neozhaoliang commented on docs/lang/articles/math/math.md
> +2. Small vector and matrix types that are analogous to those in the [OpenGL shading language](https://www.khronos.org/opengl/wiki/OpenGL_Shading_Language)(GLSL).
Same. We should use identical here.

2022-09-23 07:42 UTC, Olinaaaloompa commented on docs/lang/articles/math/math.md
> +1. Commonly-used mathematical functions that are analogous to those in Python's built-in `math` module.
What about "similar"? No difference between the two modules is mentioned in the following part.

2022-09-23 08:48 UTC, neozhaoliang commented on docs/lang/articles/math/math.md
> +1. Commonly-used mathematical functions that are analogous to those in Python's built-in `math` module.
The main difference is Taichi's math functions should be called in the Taichi scope, and has different precisions due to the init config and backends.

2022-09-23 10:08 UTC, yuanming-hu reviewed
Thanks! Some nits.

2022-09-23 10:08 UTC, yuanming-hu commented on docs/lang/articles/math/math.md
> +    Unlike `ti.Vector`, whose input data must be a 1d array as inputs, vector types created by `ti.types.vector()` have more flexible initialization routines, as we have already explained above.
```suggestion
    Unlike `ti.Vector`, whose input data must be a 1D array, vector types created by `ti.types.vector()` have more flexible ways to initialize, as explained above.
```

2022-09-23 10:08 UTC, yuanming-hu commented on docs/lang/articles/math/math.md
> ++ `ti.math.vec3` is created by `vec3 = ti.types.vector(3, float)`.
```suggestion
+ `ti.math.vec3` is simply created by `vec3 = ti.types.vector(3, float)`.
```

2022-09-23 10:08 UTC, yuanming-hu commented on docs/lang/articles/math/math.md
> ++ `ti.types.vector` is a function that accepts an integer and a primitive type, and returns a vector type. For example: `vec5f = ti.types.vector(5, float)`. `vec5f` can be used to instantiate 5D vect
```suggestion
+ `ti.types.vector` is a function that accepts an integer and a primitive type, and returns a vector type. For example: `vec5f = ti.types.vector(5, float)`. `vec5f` can then be used to instantiate 5D vectors or annotate data types in function arguments and struct members:
```

2022-09-23 14:11 UTC, Vissidarte-Herman requested changes
LGTM except for some minor editorial requests.

2022-09-23 14:11 UTC, Vissidarte-Herman commented on docs/lang/articles/math/math.md
> +Taichi's math module also supports a few [GLSL standard functions](https://registry.khronos.org/OpenGL-Refpages/gl4/index.php), they are implemented in the way that follows the GLSL standard, except
```suggestion
Taichi's math module also supports a few [GLSL standard functions](https://registry.khronos.org/OpenGL-Refpages/gl4/index.php). These functions follow the GLSL standard, except that they accept arbitrary vectors and matrices as arguments and operate on them element-wise. For example:
```

Please check if I tempered with the intended meaning.

2022-09-23 14:11 UTC, Vissidarte-Herman commented on docs/lang/articles/math/math.md
> +You can use a 2D vector of type `ti.math.vec2` to represent a complex number, the addtion/subtraction of complex numbers are just addtion/subtraction of 2D vectors, and multiplication and division ca
```suggestion
You can use a 2D vector of type `ti.math.vec2` to represent a complex number, the addtion/subtraction of complex numbers are just addtion/subtraction of 2D vectors, and multiplication and division can be performed by calling `ti.math.cmul` and `ti.math.cdiv`:
```
Shall we use `ti.math.cmul()` and `ti.math.cdiv()`?

2022-09-23 14:11 UTC, Vissidarte-Herman commented on docs/lang/articles/math/math.md
> +Taichi's math module also supports basic complex arithmetic in the form of 2D vectors.
complex arithmetric -> complex operations?

2022-09-23 14:11 UTC, Vissidarte-Herman commented on docs/lang/articles/math/math.md
> +## Complex number arithmetic
```suggestion
## Complex number operations
```
Correct?

2022-09-23 14:17 UTC, Vissidarte-Herman requested changes

2022-09-23 14:17 UTC, Vissidarte-Herman commented on docs/lang/articles/math/math.md
> +# The math module
```suggestion
# Math Module
```

2022-09-26 08:21 UTC, Vissidarte-Herman approved these changes
LGTM

2022-09-26 08:25 UTC, Olinaaaloompa approved these changes

2022-09-26 08:29 UTC, merged