[Doc] Refactor simt
taichi-dev/taichi pull request #6151
Opened 2022-09-23 07:54 UTC by neozhaoliang

2022-09-23 12:06 UTC, Vissidarte-Herman requested changes
LGTM. Minor editorial changes.

2022-09-23 12:06 UTC, Vissidarte-Herman commented on docs/lang/articles/reference/simt.md
> +For CUDA backend, Taichi now supports warp-level and block-level intrinsics that
```suggestion
For the CUDA backend, Taichi supports warp-level and block-level intrinsics, which
```

2022-09-23 12:06 UTC, Vissidarte-Herman commented on docs/lang/articles/reference/simt.md
> +Please refer to our [API docs](https://docs.taichi.graphics/api/taichi/lang/simt/warp/#module-taichi.lang.simt.warp)
```suggestion
See [Taichi's API reference](https://docs.taichi-lang.org/api/taichi/lang/simt/warp/#module-taichi.lang.simt.warp)
```

2022-09-23 12:06 UTC, Vissidarte-Herman commented on docs/lang/articles/reference/simt.md
> +Here is an example to perform data exchange within a warp in Taichi:
```suggestion
Here is an example of performing data exchange within a warp in Taichi:
```

2022-09-23 13:16 UTC, yuanming-hu approved these changes
LGTM! Thank you!

2022-09-26 08:30 UTC, Vissidarte-Herman approved these changes
LGTM

2022-09-26 08:30 UTC, merged