[Doc] Update hello world
taichi-dev/taichi pull request #6191
Opened 2022-09-28 08:19 UTC by Olinaaaloompa

Major changes:
1. Delete "optional GPU backends" in "Prerequisites";
2. Move Taichi gallery/examples to the end of the document;
3. Add `ti.loop_config(serialized=True)`;
4. Add introduction to scenario-based tutorials;
5. Make other editorial updates.

2022-09-29 03:33 UTC, Olinaaaloompa commented on docs/lang/articles/get-started/index.md
> +This line calls `ti.init()` to initialize environment variables. This function accepts several arguments to allow you to customize your runtime program. For now, we only introduce the most important
```suggestion
This line calls `ti.init()` to customize your Taichi runtime depending on the arguments passed into it. For now, we only introduce the most important argument, namely, `arch`.
```

2022-09-29 03:33 UTC, Olinaaaloompa commented on docs/lang/articles/get-started/index.md
> +You can also directly specify which GPU backend to use. For example, set `arch=ti.cuda` to run your program on CUDA. Taichi raises an error if the target architecture is unavailable.
```suggestion
You can also directly specify which GPU backend to use. For example, set `arch=ti.cuda` to run your program on CUDA. Taichi raises an error if the target architecture is unavailable. See the [Global Settings] for more information on `ti.init()`.
```

2022-09-29 03:37 UTC, Olinaaaloompa commented on docs/lang/articles/get-started/index.md
> +You can also directly specify which GPU backend to use. For example, set `arch=ti.cuda` to run your program on CUDA. Taichi raises an error if the target architecture is unavailable. See the [Global
```suggestion
You can also directly specify which GPU backend to use. For example, set `arch=ti.cuda` to run your program on CUDA. Taichi raises an error if the target architecture is unavailable. See the [Global Settings](../reference/global_settings.md) for more information on `ti.init()`.
```

2022-09-29 08:05 UTC, Vissidarte-Herman requested changes

2022-09-29 08:05 UTC, Vissidarte-Herman commented on docs/lang/articles/get-started/index.md
> +You will come across the advanced features of `field` in other scenario-based tutorials. For now, it suffices for you to understand that the field `pixels` is a dense 2D array.
```suggestion
We will introduce more advanced features of field in other scenario-based tutorials. For now, it suffices to know that the field `pixels` is a dense 2D array.
```

2022-09-29 08:05 UTC, Vissidarte-Herman commented on docs/lang/articles/get-started/index.md
> +- Taichi *supports* nested functions but *does not support* nested kernels. Calling Taichi functions recursively is *not supported for now*.
```suggestion
- Taichi *supports* nested functions but *does not support* nested kernels. Calling Taichi functions recursively is *not supported*.
```

2022-09-29 10:10 UTC, Olinaaaloompa commented
/rebase

2022-09-30 13:11 UTC, Vissidarte-Herman requested changes

2022-09-30 13:11 UTC, Vissidarte-Herman commented on docs/lang/articles/get-started/index.md
> +You can also directly specify which GPU backend to use. For example, set `arch=ti.cuda` to run your program on CUDA. Taichi raises an error if the target architecture is unavailable. See the [Global
```suggestion
You can also directly specify which GPU backend to use. For example, set `arch=ti.cuda` to run your program on CUDA. Taichi raises an error if the target architecture is unavailable. See the [Global Settings](../reference/global_settings.md) for more information about `ti.init()`.
```
See ... for more information about ...

2022-09-30 13:11 UTC, Vissidarte-Herman commented on docs/lang/articles/get-started/index.md
> +To access the full list of Taichi examples, run `ti example` instead. Other useful command lines:
```suggestion
To access the full list of Taichi examples, run `ti example`. Other useful command lines:
```

2022-09-30 13:11 UTC, Vissidarte-Herman commented on docs/lang/articles/get-started/index.md
> +The program iterates over `pixels` 1,000,000 times, and the fractal pattern stored in `pixels` is updated accordingly. Call `gui.set_image()` to set the window and `gui.show()` to display the synchro
```suggestion
The program iterates over `pixels` 1,000,000 times, and the fractal pattern stored in `pixels` is updated accordingly. Call `gui.set_image()` to set the window and `gui.show()` to display the synchronized result on your screen.
```

2022-09-30 13:11 UTC, Vissidarte-Herman commented on docs/lang/articles/get-started/index.md
> +The Julia fractal is one of the representative demos Taichi provides. Run the following command in your terminal to view more selected demos in Taichi gallery:
```suggestion
The Julia fractal is one of the representative demos Taichi provides. To view more selected demos in Taichi gallery:
```

2022-09-30 13:11 UTC, Vissidarte-Herman commented on docs/lang/articles/get-started/index.md
> +- The for loop at the outermost scope in a kernel is automatically parallelized.
```suggestion
- for loops at the outermost scope in a Taichi kernel are automatically parallelized.
```

2022-09-30 13:11 UTC, Vissidarte-Herman commented on docs/lang/articles/get-started/index.md
> +        for k in range(5):  # Not parallelized: not at the outermost scope
```suggestion
        for k in range(5):  # Not parallelized because it is not at the outermost scope
```

2022-09-30 13:11 UTC, Vissidarte-Herman commented on docs/lang/articles/get-started/index.md
> +The code snippet defines a field whose shape is (640, 320) and whose elements are floating-point data.
```suggestion
The code snippet defines a field whose shape is (640, 320) and whose elements are floating-point numbers.
```

2022-09-30 13:16 UTC, Vissidarte-Herman requested changes

2022-09-30 13:16 UTC, Vissidarte-Herman commented on docs/lang/articles/get-started/index.md
> +- A kernel *must* take type-hinted arguments and return type-hinted results. But Taichi functions do not require type hinting compulsorily. In the example above, the argument `t` in the kernel `paint
```suggestion
- A kernel *must* take type-hinted arguments and return type-hinted results. But Taichi functions do not require type hinting. In the example above, the argument `t` in the kernel `paint` is type hinted; the argument `z` in the Taichi function `complex_sqr` is not.
```
@Olinaaaloompa "require" is synonymous with "compulsory".

2022-09-30 13:20 UTC, Vissidarte-Herman requested changes

2022-09-30 13:20 UTC, Vissidarte-Herman commented on docs/lang/articles/get-started/index.md
> +Lines 9~22 define two functions, one decorated with `@ti.func` and the other with `@ti.kernel`. They are called a *Taichi function* and a *kernel*, respectively. Taichi functions and kernels are not
```suggestion
Lines 9~22 define two functions, one decorated with `@ti.func` and the other with `@ti.kernel`. They are called *Taichi function* and *kernel* respectively. Taichi functions and kernels are not executed by Python's interpreter but taken over by Taichi's JIT compiler and deployed to your parallel multi-core CPU or GPU.
```

2022-09-30 13:20 UTC, Vissidarte-Herman commented on docs/lang/articles/get-started/index.md
> +- Taichi *supports* nested functions but *does not support* nested kernels. Calling Taichi functions recursively is *not supported*.
```suggestion
- Taichi *supports* nested functions but *does not support* nested kernels. 
- Taichi *does not* support recursive Taichi function calls.
```

2022-09-30 13:24 UTC, Vissidarte-Herman requested changes

2022-09-30 13:24 UTC, Vissidarte-Herman commented on docs/lang/articles/get-started/index.md
> +You can also serialize a parallel for loop at the outermost scope via `ti.loop_config(serialize=True)`. See [Serialize a specified parallel for loop](../debug/debugging.md#serialize-a-specified-paral
```suggestion
You can also serialize a for loop at the outermost scope using `ti.loop_config(serialize=True)`. See [Serialize a specified parallel for loop](../debug/debugging.md#serialize-a-specified-parallel-for-loop) for more information.
```

2022-09-30 13:24 UTC, Vissidarte-Herman commented on docs/lang/articles/get-started/index.md
> +When writing compute-intensive tasks in Python, you can take advantage of Taichi's high performance computation by following a few extra rules. Generally, Taichi provides two decorators `@ti.func` an
```suggestion
When writing compute-intensive tasks in Python, you can take advantage of Taichi's high performance computation by following a few extra rules. Generally, Taichi provides two decorators `@ti.func` and `@ti.kernel`, which instruct Taichi to take over the implementation of the tasks. Its just-in-time (JIT) compiler compiles the decorated functions to machine code, and all subsequent calls to these functions are executed on multi-core CPUs or GPUs. In a typical compute-intensive scenario, such as a numerical simulation, Taichi can accelerate performance by 50x~100x compared with native Python code.
```

2022-09-30 13:26 UTC, Vissidarte-Herman requested changes

2022-09-30 13:26 UTC, Vissidarte-Herman commented on docs/lang/articles/get-started/index.md
> +- Frequently used math functions.
```suggestion
- Frequently-used math functions.
```

2022-09-30 13:37 UTC, Vissidarte-Herman requested changes

2022-09-30 13:37 UTC, Vissidarte-Herman commented on docs/lang/articles/get-started/index.md
> +*field* is the most important and frequently used data structure in Taichi. You can compare it to NumPy's `ndarray` or PyTorch's `tensor`. But Taichi's field is more flexible than the two counterpart
```suggestion
*field* is the most important and frequently used data structure in Taichi. You can compare it to NumPy's `ndarray` or PyTorch's `tensor`. But Taichi's field is more flexible. For example, a Taichi field can be [spatially sparse](../basic/sparse.md) and easily [switched between different data layouts](../basic/layout.md).
```

2022-09-30 13:37 UTC, Vissidarte-Herman commented on docs/lang/articles/get-started/index.md
> +- Kernels are the entry points where Taichi kicks in and takes over the task. A kernel can be called anywhere, anytime in your program, while a Taichi function can only be called from inside a kernel
```suggestion
- Kernels are the entry points where Taichi kicks in and takes over the task. A kernel can be called anywhere, anytime in your program, while a Taichi function can be called only from inside a kernel or from inside another Taichi function. In the example above, the Taichi function `complex_sqr` is called by the kernel `paint`.
```

2022-09-30 13:41 UTC, Vissidarte-Herman commented
Please resolve conflicts first

2022-09-30 14:16 UTC, Vissidarte-Herman approved these changes

2022-09-30 14:16 UTC, merged