[Doc] Update global settings
taichi-dev/taichi pull request #6201
Opened 2022-09-29 06:29 UTC by Olinaaaloompa

Editorial updates

2022-09-29 06:44 UTC, Olinaaaloompa commented on docs/lang/articles/reference/global_settings.md
> +- To disable fast math: `ti.init(fast_math=False)`, which helps prevent possible undefined math behavior
```suggestion
- To disable fast math: `ti.init(fast_math=False)`, which helps prevent possible undefined math behavior.
```

2022-09-29 06:44 UTC, Olinaaaloompa commented on docs/lang/articles/reference/global_settings.md
> +If `ti.init` is called twice, the configuration in the first call is discarded. for example:
```suggestion
If `ti.init` is called twice, the configuration in the first call is discarded. For example:
```

2022-09-30 14:08 UTC, Vissidarte-Herman requested changes

2022-09-30 14:08 UTC, Vissidarte-Herman commented on docs/lang/articles/reference/global_settings.md
> +When you call `ti.init()`, Taichi executes the following steps to initialize a specific configuration. We use the `arch` argument as an example:
"executes the following steps" is not grammatical. 
```suggestion
Taichi executes the following to initialize a specific configuration in the `ti.init()` method call. Taking the `arch` argument as an example:
```

2022-09-30 14:08 UTC, Vissidarte-Herman commented on docs/lang/articles/reference/global_settings.md
> +        Enable/disable GDB when Taichi crashes. For example, `ti.init(gdb_trigger=True)` activates GDB.
Avoid using two different terms for the same meaning. Use enables instead.

2022-09-30 14:33 UTC, merged