[doc] Update sparse matrix document
taichi-dev/taichi pull request #6719
Opened 2022-11-23 15:24 UTC by FantasyVR

Issue: #2906

2022-11-29 02:08 UTC, Olinaaaloompa requested changes

2022-11-29 02:08 UTC, Olinaaaloompa commented on docs/lang/articles/math/sparse_matrix.md
> +3. Call `x = solver.solve(b)`, where `x` is the solution and `b` is the right-hand side of the linear system. On CPU backend, `x` and `b` are numpy arrays, taichi ndarrays or taichi fileds. On CUDA b
```suggestion
3. Call `x = solver.solve(b)`, where `x` is the solution and `b` is the right-hand side of the linear system. On CPU backends, `x` and `b` can be NumPy arrays, Taichi Ndarrays, or Taichi fields. On the CUDA backend, `x` and `b` *must* be Taichi Ndarrays.
```

2022-11-29 02:08 UTC, Olinaaaloompa commented on docs/lang/articles/math/sparse_matrix.md
> +2. Fill the `builder` using `ti.kernel` function with your matrices' data.
```suggestion
2. Call `ti.kernel` to fill the `builder` with your matrices' data.
```

2022-11-30 05:03 UTC, Olinaaaloompa approved these changes

2022-11-30 05:04 UTC, strongoier approved these changes

2022-11-30 05:19 UTC, merged