[doc] field.md
taichi-dev/taichi pull request #6867
Opened 2022-12-11 22:31 UTC by vai9er

Issue: #

### Brief Summary

2022-12-13 02:46 UTC, Olinaaaloompa requested changes
I'm now a bit confused about the capitalization thing. Let's discuss it tmr.

2022-12-13 02:46 UTC, Olinaaaloompa commented on docs/lang/articles/basic/field.md
> +  Over here we are defining a
Unfinished sentence?

2022-12-14 04:02 UTC, Olinaaaloompa commented on docs/lang/articles/basic/field.md
> +- To access the `ith, jth` element of the matrix field `tensor_field`:
```suggestion
- To access the `i-th, j-th` element of the matrix field `tensor_field`:
```

2022-12-14 11:13 UTC, neozhaoliang commented on docs/lang/articles/basic/field.md
> +>>>>>>> da7bac2b5be484ec2648fe058e191497f5803384
A conflict here?

2023-01-13 08:55 UTC, Olinaaaloompa approved these changes
LGTM!

2023-01-13 08:56 UTC, merged