[doc] Update external.md
taichi-dev/taichi pull request #6869
Opened 2022-12-12 00:13 UTC by vai9er

Issue: #

### Brief Summary

2022-12-12 03:41 UTC, neozhaoliang approved these changes
Thanks, and LGTM!

2022-12-12 04:17 UTC, Olinaaaloompa requested changes

2022-12-12 04:17 UTC, Olinaaaloompa commented on docs/lang/articles/basic/external.md
> +## Data Transfer between NumPy arrays and Taichi Fields
We use the title case for document titles, and the sentence case for subheadings. So only the major words in first-level headings are capitalized,

2022-12-12 04:17 UTC, Olinaaaloompa commented on docs/lang/articles/basic/external.md
> +## Data Transfer between PyTorch/Paddle Tensors and Taichi Fields
ibid.

2022-12-12 04:17 UTC, Olinaaaloompa commented on docs/lang/articles/basic/external.md
> +4. When importing data to a struct field, export the data of the corresponding external array as **a dictionary of NumPy arrays, PyTorch tensors, or Paddle tensors** with keys being struct member nam
I think we should still use the bullet list here. We can discuss it in our next meeting.

2022-12-12 04:17 UTC, Olinaaaloompa commented on docs/lang/articles/basic/external.md
> +Not only is this code snippet is more readable than the NumPy version above, but it also runs way faster even on the CPU backend.
```suggestion
Not only is this code snippet more readable than the NumPy version above, but it also runs way faster even on the CPU backend.
```

2022-12-12 04:17 UTC, Olinaaaloompa commented on docs/lang/articles/basic/external.md
> +### Advanced
Should we avoid a single third-level heading in one section? We can discuss it.

2022-12-14 03:19 UTC, Olinaaaloompa requested changes

2022-12-14 03:19 UTC, Olinaaaloompa commented on docs/lang/articles/basic/external.md
> +1. Create a Taichi field `f`, whose shape and dtype match the shape and dtype of `arr`, and call `f.from_numpy(arr)` to copy the data in `arr` into `f`. This approach is preferred when the original a
```suggestion
- Create a Taichi field `f`, whose shape and dtype match the shape and dtype of `arr`, and call `f.from_numpy(arr)` to copy the data in `arr` into `f`. This approach is preferred when the original array is visited frequently from elsewhere in the Taichi scope (for example, in texture sampling).
```

2022-12-14 03:19 UTC, Olinaaaloompa commented on docs/lang/articles/basic/external.md
> +## Data Transfer between NumPy arrays and Taichi Fields
```suggestion
## Data transfer between NumPy arrays and Taichi fields
```

2022-12-14 03:19 UTC, Olinaaaloompa commented on docs/lang/articles/basic/external.md
> +## Data Transfer between PyTorch/Paddle Tensors and Taichi Fields
```suggestion
## Data transfer between PyTorch/Paddle tensors and Taichi fields
```

2022-12-14 03:19 UTC, Olinaaaloompa commented on docs/lang/articles/basic/external.md
> +## Using External Arrays as Taichi Kernel Arguments
```suggestion
## Using external arrays as Taichi kernel arguments
```

2022-12-14 03:19 UTC, Olinaaaloompa commented on docs/lang/articles/basic/external.md
>  Use type hint `ti.types.ndarray()` to pass external arrays as kernel arguments. For example:
```suggestion
Use type hint `ti.types.ndarray()` to pass external arrays as kernel arguments.

### An entry-level example

The following example shows the most basic way to call `ti.types.ndarray()`:
```

2022-12-14 03:19 UTC, Olinaaaloompa commented on docs/lang/articles/basic/external.md
>  This is an entry-level example to show you how to call `ti.types.ndarray()`. We now illustrate a more advanced usage of this method.
```suggestion
### Advanced usage
```

2022-12-14 03:19 UTC, Olinaaaloompa commented on docs/lang/articles/basic/external.md
> +### Advanced
```suggestion

```

2022-12-14 03:23 UTC, Olinaaaloompa approved these changes
LGTM!

2022-12-15 03:22 UTC, neozhaoliang approved these changes
Thanks!

2022-12-15 03:22 UTC, merged