[aot] C_API behavior test
taichi-dev/taichi pull request #6904
Opened 2022-12-15 02:57 UTC by damnkk

Issue: #

### Brief Summary
Added run out of memory test case.

2022-12-15 04:11 UTC, PENGUINLIONG requested changes

2022-12-15 04:11 UTC, PENGUINLIONG commented on taichi/rhi/vulkan/vulkan_api.cpp
> +  if (res == VK_ERROR_OUT_OF_DEVICE_MEMORY) {
// FIXME: (damnkk) Should be removed when RHI error codes are ready

2022-12-15 06:11 UTC, PENGUINLIONG commented
There is an on-going rafactorization to add error codes to all RHI interfaces. We don't have it for now so I'm not sure if it's a proper way to report OOM errors for the release. Or we just wait for a future commit of OOM RHI error to be merged? wdyt @bobcao3 @ailzhang

2022-12-17 12:41 UTC, ailzhang commented
IMHO it doesn't have to be blocked by the missing OOM error code in rhi refactorization as long as we add a FIXME and fix it right after the merge. Adding these tests will also help make sure the refactorization goes well.

2022-12-17 12:41 UTC, ailzhang commented on c_api/tests/c_api_behavior_test.cpp
> +    }
nit: early return after warning?

2022-12-17 12:41 UTC, ailzhang commented on c_api/tests/c_api_behavior_test.cpp
> +    TiRuntime runtime = ti_create_runtime(arch);
nit: better split these to 5 smaller / separate tests to keep tests minimal and isolated ;)

2022-12-20 09:37 UTC, PENGUINLIONG approved these changes
lgtm then. thank you!

2022-12-20 09:37 UTC, merged