[llvm] Compile the kernel arguments to a StructType
taichi-dev/taichi pull request #7441
Opened 2023-02-24 07:58 UTC by lin-hitonami

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* (to be filled)

2023-03-02 09:53 UTC, feisuzhu commented
test

2023-03-03 05:53 UTC, feisuzhu commented
ghstack bot failed: Check-run `Build and Test Windows`'s status `failure` is not success!

2023-03-03 06:30 UTC, feisuzhu commented
ghstack bot failed: PR #7441 PR #7441 check-run `Build and Test Windows`'s status `failure` is not success!

2023-03-03 08:21 UTC, feisuzhu commented
ghstack bot failed: No reviews found!

2023-03-03 08:21 UTC, feisuzhu commented
ghstack bot failed: No reviews found!

2023-03-03 08:23 UTC, feisuzhu commented
ghstack bot failed: PR #7441 is not approved yet!

2023-03-03 08:25 UTC, feisuzhu approved these changes
TESTING! NOT REALLY APPROVED!

2023-03-03 08:26 UTC, feisuzhu commented
ghstack bot failed: PR #7441 check-run `Build and Test Windows`'s status `failure` is not success!

2023-03-03 08:26 UTC, feisuzhu requested changes
TESTING!

2023-03-03 08:26 UTC, feisuzhu commented
ghstack bot failed: @feisuzhu has `CHANGES_REQUESTED` PR #7441, please resolve it first!

2023-03-03 08:38 UTC, feisuzhu commented
ghstack bot failed: @feisuzhu has stamped PR #7441 `CHANGES_REQUESTED`, please resolve it first!

2023-03-14 18:38 UTC, bobcao3 commented on taichi/codegen/llvm/codegen_llvm.cpp
> +  std::vector<llvm::Value *> gep_index;
nit:
```suggestion
  std::vector<llvm::Value *> gep_index(index.size() + 1);
```
Then index into it

2023-03-14 18:40 UTC, bobcao3 commented on taichi/codegen/llvm/codegen_llvm.cpp
> +  args_ptr = builder->CreatePointerCast(
ditto

2023-03-14 18:42 UTC, bobcao3 commented on taichi/util/bit.h
> +TI_FORCE_INLINE uint16 float_to_half(const float32 x) {
We have a F16 library submodule in the externals folder. Use that pls for IEEE correctness and hardware intrinsics on ARM CPUs

2023-03-20 09:29 UTC, ailzhang approved these changes
LGTM!

2023-03-20 09:33 UTC, lin-hitonami commented
/land

2023-03-20 09:34 UTC, closed without merging