[cpu] Remove atomics demotion for single-thread CPU targets.
taichi-dev/taichi pull request #7631
Opened 2023-03-22 07:01 UTC by turbo0628

Remove the single thread CPU atomic demotion, so that LLVM could do auto-reduction for better performance.

Issue: #7442

2023-03-22 10:04 UTC, jim19930609 approved these changes

2023-03-22 10:06 UTC, jim19930609 requested changes
Wait, demoting the atomic operation when there's no multi-threading tasks should be expected behavior? Why are we removing this logic

2023-03-24 06:27 UTC, turbo0628 commented
@lin-hitonami I'm not so sure, current test cases are all reducible and LLVM did a good job at vectorization. 

@jim19930609 It's not really expected. For single threaded CPUs, it could leverage the vector units to accelerate atomic ops, which has implicit parallelism under the hood.

2023-03-24 07:20 UTC, jim19930609 commented
> @lin-hitonami I'm not so sure, current test cases are all reducible and LLVM did a good job at vectorization.
> 
> @jim19930609 It's not really expected. For single threaded CPUs, it could leverage the vector units to accelerate atomic ops, which has implicit parallelism under the hood.

Hmmm, I still don't quite get it. Say you have an `atomic_add_i32()` which runs on single-thread CPU. How does demoting it to `add()` hampers the vector optimization?

2023-03-27 03:28 UTC, turbo0628 commented
@jim19930609  You are right. Seems that the root cause is not atomic add, it's more about how to properly deal with global tmps. Let's use a simpler example program:
```Python
@ti.kernel
def calc_sum(NPTS:int)->float:
    s = 0.0
    for i in range(0,(NPTS)):
       s += 1.0
    return s
```


If I turn on the atomic add demotion (as we are doing in current. master), the CHI IR is
```llvm
kernel {
$0 = offloaded range_for(0, 1) grid_dim=0 block_dim=1 
body {
  <f64> $1 = const 1.0
  <i32> $2 = const 512
  <i32> $3 = loop $0 index 0
  <*i32> $4 = global tmp var (offset = 0 B)
  <i32> $5 = global load $4
  <i32> $6 = max $5 $2
  <i32> $7 = mul $6 $3
  <i32> $8 = add $7 $6
  <i32> $9 = min $5 $8
  $10 : for in range($7, $9) block_dim=1 {
    <*f64> $11 = global tmp var (offset = 8 B)
    <f64> $12 = global load $11
    <f64> $13 = add $12 $1
    $14 : global store [$11 <- $13]
  }
}
}
```

However if we reserve the atomic add, it then becomes

```llvm
kernel {
$0 = offloaded range_for(0, tmp(offset=0B)) grid_dim=0 block_dim=32 
tls prologue {
  <*f64> $1 = thread local ptr (offset = 0 B)
  <f64> $2 = const 0.0
  $3 : global store [$1 <- $2]
}
body {
  <*f64> $4 = thread local ptr (offset = 0 B)
  <f64> $5 = const 1.0
  <f64> $6 = global load $4
  <f64> $7 = add $6 $5
  $8 : global store [$4 <- $7]
}
tls_epilogue {
  <*f64> $9 = thread local ptr (offset = 0 B)
  <f64> $10 = global load $9
  <*f64> $11 = global tmp var (offset = 8 B)
  <f64> $12 = atomic add($11, $10)
}
}
```
with TLS explicitly enabled. 

So, the problem is that global tmps are not properly transformed when atomic add is demoted. We might have a better fix than brutally keep the atomic add :)

2023-03-29 09:34 UTC, turbo0628 commented
The performance differences of tuning the atomics on and off is ignorable. The test case is single threaded saxpy.
<img width="594" alt="image" src="https://user-images.githubusercontent.com/5178486/228491902-ac542c01-d7ff-483e-bf01-246e3a81ae55.png">

2023-03-29 10:39 UTC, jim19930609 approved these changes

2023-03-29 15:00 UTC, merged