[Lang] Fix the api doc search problem
taichi-dev/taichi pull request #7918
Opened 2023-05-04 07:51 UTC by neozhaoliang

Users cannot find the definitions of `inf, nan, pi, e` from the math module on the doc site. This PR tries to fix this.

2023-05-04 10:16 UTC, ailzhang requested changes
nah I don't think this can fix the problem, for example, https://docs.taichi-lang.org/search?category=api&q=vec2 didn't show up in search result but it has a docstring.

2023-05-05 06:52 UTC, neozhaoliang commented
I have tested the docstring-gen repo, sphinx correctly generated items for `vec2/3/4` because [they have docstrings](https://github.com/taichi-dev/docstring-gen/blob/master/experimental/_autoapi_templates/python/module.rst?plain=1#L10), you can verify this here: https://docs.taichi-lang.org/api/taichi/math/

The problem should happen on the algolia part.

2023-05-05 06:54 UTC, ailzhang commented
@neozhaoliang agh I see thanks! shall we compile a list of all apis that are missing docstrings (thus hidden in doc site) and decide whether we want to add docstrings for them as well?

2023-05-05 07:16 UTC, neozhaoliang commented
Sure, opened an issue to record: https://github.com/taichi-dev/taichi/issues/7924

2023-05-06 05:01 UTC, ailzhang approved these changes

2023-05-06 05:01 UTC, merged